// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6P63rkbBF0G2JgJ_O_D2swaSBbbsECaE',
    appId: '1:103766208578:web:1772d29d04f8faed6efddb',
    messagingSenderId: '103766208578',
    projectId: 'e-shop-93383',
    authDomain: 'e-shop-93383.firebaseapp.com',
    storageBucket: 'e-shop-93383.firebasestorage.app',
    measurementId: 'G-ZYKV5T7CBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCywact8iU45ilJMW0DjHd8CdfcY09eRzI',
    appId: '1:103766208578:android:a3356465c6f60f9a6efddb',
    messagingSenderId: '103766208578',
    projectId: 'e-shop-93383',
    storageBucket: 'e-shop-93383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtyF_Rv5RxSre2tRI0BpD1PikUdSNRFk',
    appId: '1:103766208578:ios:1ee3ed4d90f896326efddb',
    messagingSenderId: '103766208578',
    projectId: 'e-shop-93383',
    storageBucket: 'e-shop-93383.firebasestorage.app',
    iosClientId: '103766208578-ig0ej00imgttng0vooquv1uhds6bd3b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.productHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtyF_Rv5RxSre2tRI0BpD1PikUdSNRFk',
    appId: '1:103766208578:ios:1ee3ed4d90f896326efddb',
    messagingSenderId: '103766208578',
    projectId: 'e-shop-93383',
    storageBucket: 'e-shop-93383.firebasestorage.app',
    iosClientId: '103766208578-ig0ej00imgttng0vooquv1uhds6bd3b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.productHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6P63rkbBF0G2JgJ_O_D2swaSBbbsECaE',
    appId: '1:103766208578:web:36a639d7625e665f6efddb',
    messagingSenderId: '103766208578',
    projectId: 'e-shop-93383',
    authDomain: 'e-shop-93383.firebaseapp.com',
    storageBucket: 'e-shop-93383.firebasestorage.app',
    measurementId: 'G-D931X8ZHCY',
  );
}
